"""create assignment table

Revision ID: 02594c7016b7
Revises: 62cb4dc60407
Create Date: 2026-06-25 16:49:11.667307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02594c7016b7'
down_revision: Union[str, Sequence[str], None] = '62cb4dc60407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('assignment_ref', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('assignments')
    # ### end Alembic commands ###
