"""users and courses tables

Revision ID: 573b7f0f9b13
Revises: 
Create Date: 2026-06-24 14:01:06.314029

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from app.core.config.config import settings
import uuid


# revision identifiers, used by Alembic.
revision: str = '573b7f0f9b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    connection = op.get_bind()

    roles = settings.ROLES
    role_ids = settings.ROLE_IDS
    for i in range (0, len(role_ids)):
        connection.execute(
            sa.text(
                """
                    INSERT INTO roles (
                        role_id,
                        role_name
                    ),
                    values(
                        :role_id,
                        :role_name
                    )
                """)
                [
                    {
                        "role_id": role_ids[i],
                        "role_name": roles[i]
                    }
                ]
            )

    ###### --------- seed super admin ------------------########
    connection.execute(
        sa.text(
            """
            INSERT INTO users (
                user_id,
                email,
                hashed_password,
                is_deleted,
                is_active,
                created_at
            ),
            values (
                :user_id,
                :email,
                :hashed_password,
                :is_deleted,
                :is_acctive,
                created_at
            )
            """)
            [
                {
                    "user_id" : settings.SUPERADMIN_ID,
                    "email": settings.SUPERADMIN_EMAIL,
                    "hashed_password": PasswordHelper.hash_password(settings.SUPERADMIN_PASSWORD),
                    "is_deleted": False,
                    "is_active": True,
                    "created_at": datetime.now()
                }
            ]
    )

    connection.execute(
        sa.text(
            """
            INSERT INTO user_role (
                id,
                role_id,
                user_id,
                assigned_at
            ),
            values (
                :id,
                :role_id,
                :user_id,
                :assigned_at
            )
            """)
            [
                {
                    "id": uuid.uuid4(),
                    "role_id": settings.ROLE_IDS[0],
                    "user_id": settings.SUPERADMIN_ID,
                    "assigned_at": datetime.now()
                }
            ]
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
