"""submission and score tables

Revision ID: e4dc76a07173
Revises: baae42bf4b5d
Create Date: 2026-06-26 09:47:57.879048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dc76a07173'
down_revision: Union[str, Sequence[str], None] = 'baae42bf4b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submission_ref', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('submissions')
    # ### end Alembic commands ###
