"""add cohorts table and column cohort_id in course table

Revision ID: f94269fa06fe
Revises: 573b7f0f9b13
Create Date: 2026-06-25 09:30:10.491748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94269fa06fe'
down_revision: Union[str, Sequence[str], None] = '573b7f0f9b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('cohort_name', sa.String(), nullable=False),
    sa.Column('cohort_description', sa.Text(), nullable=False),
    sa.Column('cohort_admin', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_admin'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.add_column('courses', sa.Column('cohort_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'courses', 'cohorts', ['cohort_id'], ['cohort_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'cohort_id')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
